app = <APP_NAME>  # Replace with your unique app name, ex: 'vaultwarden-hoya'
primary_region = 'nrt'

# To skip the GCP setup, please uncomment the section below.
# [build]
#   image = "vaultwarden/server:latest"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  BUCKET_NAME = <BUCKET_NAME>  # Replace with your GCloud bucket name

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
